# Generated by Django 3.1.3 on 2020-11-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201128_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ea',
        ),
    ]
