# Generated by Django 3.1.3 on 2020-11-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_ea'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ea',
            name='ea',
            field=models.ManyToManyField(to='account.Profile'),
        ),
    ]
