# Generated by Django 3.1.3 on 2020-11-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ea_ea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ea',
            name='ea',
        ),
    ]
